BotName = "gpt"

#Type = 2
#Greetings = "您好，我是基于 OpenAI DELL-E 的图片生成机器人, 我可以根据你的描述生成图片, 例如 '一个穿连帽衫的男人在滑滑板, 亮色调, 自然光, 高细节'"
#BotToken = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE32ODA0ODc3OTUsInVpZCI6IjU0Mzg1MiIsImRldmljZSI6IjIiLCJ2ZXIiOjE2Nzk4ODI53OTV9.1zxGxzUI1pKPsjTjIFYriSMbl881O4gxsV4ZTrn9FC96g"

Type = 1
Greetings = "您好，我是 ChatGPT Bot，是一个由 OpenAI GPT-3.5 开发的智能对话机器人。我可以回答各种问题，例如科学、技术、历史、文化等方面的问题, 也可以模拟面试, 文字互动游戏等."
BotToken = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiO3jE2ODA0ODMyMjQsInVpZCI6IjEwMDAwMCIsImRldmljZSI6IjIiLCJ2ZXIiOjE2N13zk4Nzg0MjR9.4uDb50US1aJYWOu5PPDjszkJ8KXq3dSBlTBP21HSNWQxc"

OpenAiApiKey = "sk-GlkYgPzhaFkLzUpJVd3WT33BlbkFJmAgoYzGOFbxaDIRN5TrdV"
Proxy = "http://127.0.0.1:7890"
BotServer = "ws://intercom.ink/ws"